"""
Django settings for eatpan_core project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file if it exists
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-kh6&spdc!r9@v3@v7nhi0b3p!w3xj)i%rc795rz_uc)so-0b_@')
SUPABASE_JWT_SECRET = os.environ.get('SUPABASE_JWT_SECRET')

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'eatpan_core.authentication.SupabaseJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}

# Check if we are running in Render production or local dev
IS_RENDER = os.environ.get('RENDER', 'False') == 'True'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_RENDER

ALLOWED_HOSTS = ['*']
if IS_RENDER:
    # If Render provides a specific hostname via RENDER_EXTERNAL_HOSTNAME, add it
    RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
    if RENDER_EXTERNAL_HOSTNAME:
        ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CORS_ALLOW_ALL_ORIGINS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'recipes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eatpan_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eatpan_core.wsgi.application'

# Database Setup (Supports PostgreSQL via Supabase or Local Docker automatically)
# Uses dj_database_url to parse DATABASE_URL environment variable

DATABASE_URL = os.environ.get('DATABASE_URL')
CLOUD_DATABASE_URL = os.environ.get('CLOUD_DATABASE_URL')
PEER1_DATABASE_URL = os.environ.get('PEER1_DATABASE_URL')
PEER2_DATABASE_URL = os.environ.get('PEER2_DATABASE_URL')
PEER3_DATABASE_URL = os.environ.get('PEER3_DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Fallback to local Docker postgres if DATABASE_URL is somehow missing
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'postgres',
            'USER': 'postgres',
            'PASSWORD': 'your-super-secret-and-long-postgres-password',
            'HOST': 'supabase-db',
            'PORT': '5432',
        }
    }


def _add_db(alias: str, url: str | None):
    if not url:
        return
    DATABASES[alias] = dj_database_url.parse(
        url,
        conn_max_age=600,
        conn_health_checks=True,
    )


_add_db('cloud', CLOUD_DATABASE_URL)
_add_db('peer1', PEER1_DATABASE_URL)
_add_db('peer2', PEER2_DATABASE_URL)
_add_db('peer3', PEER3_DATABASE_URL)

SYNC_DB_ALIASES = [alias for alias in ['default', 'peer1', 'peer2', 'peer3', 'cloud'] if alias in DATABASES]

# Node identity for sync metadata
NODE_ID = os.environ.get('NODE_ID', 'local_a')


# NATS JetStream (Sync Broker)
NATS_URL = os.environ.get('NATS_URL', 'nats://nats:4222')
NATS_STREAM = os.environ.get('NATS_STREAM', 'eatpan_sync')
NATS_SUBJECT = os.environ.get('NATS_SUBJECT', 'eatpan.sync')
NATS_DURABLE = os.environ.get('NATS_DURABLE', f'eatpan_sync_{NODE_ID}')


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cache settings using Valkey (Redis compatible)
REDIS_URL = os.environ.get('REDIS_URL', 'redis://valkey_cache:6379/1')

# Separate Redis/Valkey endpoint for the sync broker (must be shared between nodes).
# If not provided, falls back to REDIS_URL (single-node dev).
SYNC_BROKER_REDIS_URL = os.environ.get('SYNC_BROKER_REDIS_URL', REDIS_URL)

if IS_RENDER and not os.environ.get('REDIS_URL'):
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        },
        "broker": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": SYNC_BROKER_REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        },
    }
