# Generated by Django 5.0.14 on 2026-04-05 00:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_author_recipe_is_public_userprofile'),
    ]

    def _backfill_uuid(apps, schema_editor, model_name: str):
        Model = apps.get_model('recipes', model_name)
        db_alias = schema_editor.connection.alias
        for obj in Model.objects.using(db_alias).filter(uuid__isnull=True).only('id'):
            Model.objects.using(db_alias).filter(pk=obj.pk).update(uuid=uuid.uuid4())


    def backfill_recipe_uuid(apps, schema_editor):
        Migration._backfill_uuid(apps, schema_editor, 'Recipe')


    def backfill_recipebook_uuid(apps, schema_editor):
        Migration._backfill_uuid(apps, schema_editor, 'RecipeBook')


    def backfill_userprofile_uuid(apps, schema_editor):
        Migration._backfill_uuid(apps, schema_editor, 'UserProfile')

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='uuid',
            field=models.UUIDField(null=True, editable=False, db_index=True),
        ),
        migrations.RunPython(backfill_recipe_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='recipe',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, db_index=True),
        ),
        migrations.AddField(
            model_name='recipebook',
            name='uuid',
            field=models.UUIDField(null=True, editable=False, db_index=True),
        ),
        migrations.RunPython(backfill_recipebook_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='recipebook',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, db_index=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(null=True, editable=False, db_index=True),
        ),
        migrations.RunPython(backfill_userprofile_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, db_index=True),
        ),
    ]
