# Generated by Django 5.0.14 on 2026-04-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_mediaasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_uuid', models.UUIDField(db_index=True)),
                ('op', models.CharField(max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('node_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_outbox',
            },
        ),
        migrations.AddIndex(
            model_name='syncoutbox',
            index=models.Index(fields=['entity_type', 'published_at', 'created_at'], name='sync_outbox_pub_idx'),
        ),
    ]
