# Generated by Django 5.0.14 on 2026-04-17 13:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_syncoutbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comment_reactions',
            },
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.JSONField(default=dict, verbose_name='Дані категорії (JSONB)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'db_table': 'recipe_categories',
            },
        ),
        migrations.CreateModel(
            name='RecipeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.TextField(verbose_name='Текст коментаря')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recipe_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji_type', models.CharField(max_length=50, verbose_name='Тип емодзі (напр. fire, star)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recipe_reactions',
            },
        ),
        migrations.CreateModel(
            name='UserRecipeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_planned', models.BooleanField(default=False, verbose_name='Сплановано')),
                ('is_cooked', models.BooleanField(default=False, verbose_name='Приготовлено')),
                ('cooked_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата приготування')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Строк придатності')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Локація (Холодильник, шафа)')),
                ('cook_count', models.IntegerField(default=0, verbose_name='Кількість приготувань юзером')),
                ('personal_digestion_time', models.CharField(blank=True, max_length=100, verbose_name='Час засвоювання (особистий)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_recipe_states',
            },
        ),
        migrations.RenameIndex(
            model_name='syncoutbox',
            new_name='sync_outbox_entity__777e55_idx',
            old_name='sync_outbox_pub_idx',
        ),
        migrations.AddField(
            model_name='recipe',
            name='repost_count',
            field=models.IntegerField(default=0, verbose_name='Кількість репостів'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='share_count',
            field=models.IntegerField(default=0, verbose_name='Кількість відправок'),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipecomment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='recipes.recipecomment'),
        ),
        migrations.AddField(
            model_name='recipereaction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrecipestate',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='userrecipestate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='commentreaction',
            unique_together={('comment', 'user', 'emoji_type')},
        ),
        migrations.AlterUniqueTogether(
            name='recipereaction',
            unique_together={('recipe', 'user', 'emoji_type')},
        ),
        migrations.AlterUniqueTogether(
            name='userrecipestate',
            unique_together={('user', 'recipe')},
        ),
    ]
