# Generated by Django 5.0.14 on 2026-04-19 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_commentreaction_recipecategory_recipecomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account',
            field=models.JSONField(blank=True, default=dict, verbose_name='Account Settings'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inbox',
            field=models.JSONField(blank=True, default=dict, verbose_name='Messages & Notifications'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meal_plan',
            field=models.JSONField(blank=True, default=dict, verbose_name='Meal Plan Data'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pantry',
            field=models.JSONField(blank=True, default=dict, verbose_name='Pantry Inventory'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shopping',
            field=models.JSONField(blank=True, default=dict, verbose_name='Shopping Lists'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social',
            field=models.JSONField(blank=True, default=dict, verbose_name='Social Context'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Generic User Data'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tasks',
            field=models.JSONField(blank=True, default=dict, verbose_name='Задачі користувача'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('discount_pct', models.IntegerField(default=0)),
                ('promo_type', models.CharField(choices=[('discount', 'Discount'), ('gift', 'Gift')], default='discount', max_length=20)),
                ('max_uses', models.IntegerField(default=1)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promos', to=settings.AUTH_USER_MODEL)),
                ('linked_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe')),
            ],
            options={
                'db_table': 'promo_codes',
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('gifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifted_promos', to=settings.AUTH_USER_MODEL)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='recipes.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promo_code_usages',
            },
        ),
    ]
